# Hey Emacs, this is a -*- makefile -*-

#############################
# Defina aqui todos os arquivos do seu projeto a serem compilados. O nome
# do arquivo principal (sem a extensão) deve ser colocado na variável
# MAIN_FILE.  Este nome será o nome dado ao arquivo binário resultante,
# assim como a vários arquivos auxiliares criado na compilação.

# Se seu projeto tem apenas um arquivo-fonte, tire todos os arquivos
# da definição da variável SOURCES abaixo, deixando apenas
# $(MAIN_FILE).c.

# Se estiver programando em outra linguagem que não C, altere
# apropriadamente a extensão de $(MAIN_FILE).c

MAIN_FILE := main
SOURCES := $(MAIN_FILE).c

#############################
# Não modifique a linha abaixo

include Makefile_base
